# -*- coding: utf-8 -*-
"""
/***************************************************************************
 NomVoie
                                 A QGIS plugin
 NomVoie
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-04-26
        git sha              : $Format:%H$
        copyright            : (C) 2022 by NomVoie
        email                : NomVoie@NomVoie.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from numbers import Number
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication, Qt
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction
# Initialize Qt resources from file resources.py
from .resources import *

from qgis.core import QgsProject
from qgis.core import QgsVectorLayer
from qgis.core import QgsDataSourceUri
# Import the code for the DockWidget
from .NomVoie_dockwidget import NomVoieDockWidget
import os.path
import csv
from qgis.core import NULL
import psycopg2


class NomVoie:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface

        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)

        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'NomVoie_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&NomVoie')
        # TODO: We are going to let the user set this up in a future iteration
        self.toolbar = self.iface.addToolBar(u'NomVoie')
        self.toolbar.setObjectName(u'NomVoie')
        #initialisation de la commune
        self.commune =str("")
        self.tble_voirie = str("")
        #print "** INITIALIZING NomVoie"

        self.pluginIsActive = False
        self.dockwidget = None


    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallBytypologie
        return QCoreApplication.translate('NomVoie', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action


    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/NomVoie/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u''),
            callback=self.run,
            parent=self.iface.mainWindow())

    #--------------------------------------------------------------------------

    def onClosePlugin(self):
        """Cleanup necessary items here when plugin dockwidget is closed"""

        #print "** CLOSING NomVoie"

        # disconnects
        self.dockwidget.closingPlugin.disconnect(self.onClosePlugin)

        # remove this statement if dockwidget is to remain
        # for reuse if plugin is reopened
        # Commented next statement since it causes QGIS crashe
        # when closing the docked window:
        # self.dockwidget = None

        self.pluginIsActive = False


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""

        #print "** UNLOAD NomVoie"

        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&NomVoie'),
                action)
            self.iface.removeToolBarIcon(action)
        # remove the toolbar
        del self.toolbar
    #--------------------------------------------------------------------------
    SCHEMA="public"
    DBNAME ="bdpada"
    HOST ="127.0.0.1"
    PORT = "5432"
    USERNAME=''
    PASSWORD=''
    connstr=""
    #--------------------------------------------------------------------------
    def log(self):
        uri = QgsDataSourceUri()
        self.USERNAME = str(self.dockwidget.op_name_lst_2.text())
        self.PASSWORD = str(self.dockwidget.pass_line.text()) #  #Récuperation du mot de passe
        self.HOST=str(self.dockwidget.IP_name.text())
        self.PORT=str(self.dockwidget.PORT_name.text())
        self.tble_voirie=str(self.dockwidget.TbleVorieName.currentText())
        self.connstr="dbname='" + self.DBNAME + "' host='" + self.HOST + "' port='"+self.PORT+ "' user='" + self.USERNAME + "' password='" + self.PASSWORD + "'"
        self.commune  = str(self.dockwidget.op_name_lst_5.currentText()) #récupération de la valeur de la combo commune
        if self.USERNAME != "" and self.PASSWORD != "" and self.tble_voirie!="":
            uri.setConnection(self.HOST, self.PORT, self.DBNAME, self.USERNAME, self.PASSWORD )
            commune=str(self.dockwidget.op_name_lst_5.currentText())
            uri.setDataSource('public', "toponymes",None,"typologie!='Routes Structurantes'")
            table = QgsVectorLayer(uri.uri(), "toponymes", "postgres")
            QgsProject.instance().addMapLayer(table)
            # self.iface.messageBar().pushInfo("Info",": oui!!!")
            if commune=='TOUS':
                uri.setDataSource('public', self.tble_voirie,"geom","atelier=1")
            else:
                ip='"atelier"=1 and ("commune"='+"'"+commune+"' or "+'"commune"='+"'INTERCOMMUNAL')"
                self.dockwidget.label_18.setText(commune+' Rue Navigateur')
                uri.setDataSource('public', self.tble_voirie,"geom",ip)
            vlayer = QgsVectorLayer(uri.uri(), self.tble_voirie, "postgres")
            QgsProject.instance().addMapLayer(vlayer)


            self.ComboCom()
            self.selectTypo()
            self.TrieTypo()
            self.dockwidget.TbleVorieName.addItem(str(self.tble_voirie))
            self.loadList()
            self.dockwidget.toolBox.setCurrentIndex(1)
        else:
            self.iface.messageBar().pushInfo("Info",": Nom d'utilisateur ou mot de passe ou table voirie vide!!!")

    def log_1(self):
        uri           = QgsDataSourceUri()
        # self.USERNAME = str(self.dockwidget.op_name_lst_2.text())
        # self.PASSWORD = str(self.dockwidget.pass_line.text()) #  #Récuperation du mot de passe
        # self.HOST=str(self.dockwidget.IP_name.text())
        # self.PORT=str(self.dockwidget.PORT_name.text())
        self.tble_voirie=str(self.dockwidget.TbleVorieName.currentText())
        # self.connstr="dbname='" + self.DBNAME + "' host='" + self.HOST + "' port='"+self.PORT+ "' user='" + self.USERNAME + "' password='" + self.PASSWORD + "'"
        #self.commune  = str(self.dockwidget.op_name_lst_5.currentText()) #récupération de la valeur de la combo commune
        self.commune  = str(self.dockwidget.Commune.currentText()) #récupération de la valeur de la combo commune
        uri.setDataSource('public', "toponymes",None,"typologie!='Routes Structurantes'")
        table         = QgsVectorLayer(uri.uri(), "toponymes", "postgres")
        QgsProject.instance().addMapLayer(table) #ouverture de la couche toponymes
        
        #-----------------------------------------------------------------------------------------------------------------------#
        #                   Si la commune est égale a 'TOUS' ouvrir la couche 'voirie_pada_test' sinon                               #
        #                   ouvrir uniquement la couche 'voirie_pada_test' avec la commune sélectionnée                              #
        #-----------------------------------------------------------------------------------------------------------------------#
        if self.commune=='TOUS':
            self.iface.messageBar().pushInfo("Info",self.tble_voirie)
            uri.setDataSource('public', self.tble_voirie,"geom","atelier=1")
        else:
            ip = '"atelier"=1 and ("commune"='+"'"+self.commune+"' or "+'"commune"='+"'INTERCOMMUNAL')"
            self.dockwidget.label_18.setText(self.commune+' Rue Navigateur')
            uri.setDataSource('public', self.tble_voirie,"geom",ip)
        vlayer = QgsVectorLayer(uri.uri(), self.tble_voirie, "postgres")
        QgsProject.instance().addMapLayer(vlayer)
        self.iface.messageBar().pushInfo("Info",uri)


        self.TrieTypo()
        self.selectTypo()
        self.loadList()

    def select(self):
        self.dockwidget.comboBox_trie.setCurrentIndex (0)
        self.selectTypo()
        #self.dockwidget.radioButton_9.setChecked (True)
        self.selectNom()



    def loadList(self):
        lists = QgsProject.instance().mapLayersByName("toponymes")[0] #récupération de la table toponymes
        lista = sorted(lists.getFeatures(),key=lambda feature:feature["id"]) #trie de la table toponyme par ordre 'id'
        for i in lista: #pour chaque ligne de la table toponyme ajouter dans la liste de nom proposer
            if self.commune!="TOUS":
                if i["observation"]==None and i["nom_propose"]!=NULL and i["commune"]==self.commune:
                    self.dockwidget.codl.addItem(str(i["nom_propose"]))
            else:
                if i["observation"]==None and i["nom_propose"]!=NULL:
                    self.dockwidget.codl.addItem(str(i["nom_propose"]))

    currentVoieIndex=-1
    gid=0
    comm=''
    id_voie=0
    pro=False


    def ComboCom(self):
        self.dockwidget.Commune.clear()
        self.dockwidget.Commune.addItem("TOUS")
        # self.dockwidget.op_name_lst_5.clear()
        # self.dockwidget.op_name_lst_5.addItem("TOUS")
        uniques     = []
        self.exists = False
        #cond        = "commune='"+str(self.commune)+"'"
        #self.iface.messageBar().pushInfo("Info",cond)
        lists   = QgsProject.instance().mapLayersByName("toponymes")[0] #récupération de la table toponymes
        lista=sorted(lists.getFeatures(),key=lambda feature:feature["id"])
        for i in lista: #pour chaque ligne de la table toponyme ajouter dans la liste de nom proposer
            if i["observation"]!=NULL and i["commune"]!=NULL:
                self.exists = False
                for unique in uniques:
                    if str(i["commune"]) == str(unique["commune"]):
                        self.exists=True
                if self.exists == False:
                    self.dockwidget.Commune.addItem(str(i["commune"]))
                    # self.dockwidget.op_name_lst_5.addItem(str(i["commune"]))
                    uniques.append(i)


    def selectTypo(self): #remplissage de la combo 'comboBox_trie' trier les typologies par commune
        self.dockwidget.comboBox_trie.clear()
        self.dockwidget.comboBox_trie.addItem("TOUS")
        uniques     = []
        self.exists = False
        cond        = "commune='"+str(self.commune)+"'"
        #self.iface.messageBar().pushInfo("Info",cond)
        lists   = QgsProject.instance().mapLayersByName("toponymes")[0] #récupération de la table toponymes
        if self.commune=='INTERCOMMUNAL':
            lista=sorted(lists.getFeatures(),key=lambda feature:feature["id"])
        else:
            lista=sorted(lists.getFeatures(cond),key=lambda feature:feature["id"])
        for i in lista: #pour chaque ligne de la table toponyme ajouter dans la liste de nom proposer
            if i["observation"]==None:
                self.exists = False
                for unique in uniques:
                    if str(i["typologie"]) == str(unique["typologie"]):
                        self.exists=True
                if self.exists == False:
                    self.dockwidget.comboBox_trie.addItem(str(i["typologie"]))
                    uniques.append(i)

    #trier les noms proposer par typologie
    def TrieTypo(self):

        comboTrie = self.dockwidget.comboBox_trie.currentText()
        if comboTrie =="TOUS":
            #self.iface.messageBar().pushInfo("Info","exsecution ")
            self.selectNom()
        else:
            tip = ''
            c   = False
            self.dockwidget.label_8.setText('')
            layer             = QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
            selected_features = layer.selectedFeatures()
            print(len(selected_features))
            print(c)
            if len(selected_features)!=0:
                print('da')
                for j in selected_features:
                    tip          = j['type_voie']
                    com          = j["commune" ]
                    self.comm    = j["commune" ]
                    self.dockwidget.label_8.setText(tip)
                    self.id_voie = j["gidati"]
                print(tip)
                #self.iface.messageBar().pushInfo("Info",comboTrie)

                inter ="commune='"+str(com)+"' and typologie='"+str(comboTrie)+"'"
                print(inter)
                #self.iface.messageBar().pushInfo("Info",inter)
                lists = QgsProject.instance().mapLayersByName("toponymes")[0]
                if com=='INTERCOMMUNAL':
                    lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
                else:
                    lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
                self.dockwidget.codl_5.clear()
                print(len(lista))
                for i in lista:
                    #self.iface.messageBar().pushInfo("Info",str(i["nom_propose"]))
                    self.gid= i["id"]
                    #print(self.gid)
                    c       = True
                    self.pro= True
                    if i["observation"]==None and i["nom_propose"]!=NULL:
                        if com=='INTERCOMMUNAL':
                            self.dockwidget.codl_5.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
                        else:
                            self.dockwidget.codl_5.addItem(str(i["nom_propose"]))
                if c==False and self.pro==False:

                    for i in lista:
                        self.dockwidget.codl_5.addItem(str(i["nom_propose"]))



    def selectNom(self):
        tip=''
        c=False
        self.pro=False
        self.dockwidget.label_8.setText('')
        #self.dockwidget.radioButton_9.setChecked (True)
        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        selected_features = layer.selectedFeatures()
        if len(selected_features)!=1:
                self.iface.messageBar().pushInfo("Info",": Plusieurs routes sont sélectionnées ou aucune voie n'est sélectionnée. Sélectionnez-en un seul!!!")
                self.dockwidget.codl.clear()
                return
        print(len(selected_features))
        print(c)
        if len(selected_features)!=0:
            print('da')
            for j in selected_features:
                if j['type_voie'] =='Boulevard':
                    tip='Boulevard'

                else:
                    if j['type_voie']=='Avenue':
                        tip='Avenue'
                    else:
                        tip='Rue'

                com=j["commune" ]
                self.comm=j["commune" ]
                self.dockwidget.label_8.setText(str(tip))
                self.id_voie=j["id_voie"]
            print(tip)
            inter="commune='"+str(com)+"'"
            print(inter)
            lists = QgsProject.instance().mapLayersByName("toponymes")[0]
            if com=='INTERCOMMUNAL':
                lista=sorted(lists.getFeatures(),key=lambda feature:feature["id"])
            else:
                lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
            self.dockwidget.codl.clear()
            print('lungime:'+str(len(lista)))

            for i in lista:
                self.gid=i["id"]
                    #print(self.gid)
                c=True
                self.pro=True
                if i["observation"]==None:
                    if com=='INTERCOMMUNAL':
                        self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
                    else:
                        self.dockwidget.codl.addItem(str(i["nom_propose"]))
                """else:
                    if tip!=1 and tip!=2:
                        if i["categorie"]==None:
                            self.gid=i["id"]
                            #print(self.gid)
                            c=True
                            self.pro=True
                            if i["observation"]==None:
                                if com=='INTERCOMMUNAL':
                                    self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
                                else:
                                    self.dockwidget.codl.addItem(str(i["nom_propose"]))"""

            if c==False:
               for i in lista:
                   self.dockwidget.codl.addItem(str(i["nom_propose"]))
                   self.dockwidget.label_8.setText(tip+': 0 Nom(s) Proposée')
                   self.pro=False
        else:
            self.dockwidget.codl.clear()
            self.loadList()

    def Next(self,feature):

        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        self.blocks = sorted(layer.getFeatures(),key=lambda feature:feature["id"])
        max=len(self.blocks)
        self.currentVoieIndex=self.currentVoieIndex+1
        if self.currentVoieIndex>max-1:
            self.currentVoieIndex=0
        feature1=self.blocks[self.currentVoieIndex]
        while feature1["new_name"] != NULL:
            print('next')
            print(feature1["new_name"])
            self.currentVoieIndex=self.currentVoieIndex+1
            print(self.currentVoieIndex)
            print(max)
            if self.currentVoieIndex>max-1:
                self.currentVoieIndex=0
            feature1=self.blocks[self.currentVoieIndex]
            #print(self.currentVoieIndex)
        if self.currentVoieIndex>max-1:
            self.currentVoieIndex=0

        feature=self.blocks[self.currentVoieIndex]
        #if  feature["work_state"] != 'C0':
        self.ZoomToFeature(feature)

    def Prev(self,feature):
        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        self.blocks = sorted(layer.getFeatures(),key=lambda feature:feature["id"])
        max=len(self.blocks)
        self.currentVoieIndex=self.currentVoieIndex-1
        if self.currentVoieIndex<0:
            self.currentVoieIndex=max-1
        feature1=self.blocks[self.currentVoieIndex]
        while feature1["new_name"] != NULL:
            self.currentVoieIndex=self.currentVoieIndex-1
            feature1=self.blocks[self.currentVoieIndex]
            #print(self.currentVoieIndex)
        if self.currentVoieIndex<0:
            self.currentVoieIndex=max-1

        feature=self.blocks[self.currentVoieIndex]
        self.ZoomToFeature(feature)

    def ZoomToFeature(self,feature):
        box = feature.geometry().buffer(20,2).boundingBox()
        self.iface.mapCanvas().setExtent(box)
        self.iface.mapCanvas().refresh()
        layer = self.iface.activeLayer()
        layer.selectByExpression(" \"id_voie\" = '{}' ".format(feature['id_voie']))


    def write(self):
        if len(self.dockwidget.codl.selectedItems()) != 0:
            z=str(self.dockwidget.codl.currentItem().text())

        else:
            self.iface.messageBar().pushInfo("Info",":Sélectionnez-en un nom ! !!")
            return
        if self.comm!='INTERCOMMUNAL':
            ip="nom_propose="+'"'+str(z)+'"'+" and commune='"+self.comm+"'"
            print(ip)
        else:
            print(str(z).split('==>'))
            p=str(z).split('==>')
            ip="nom_propose="+'"'+str(z)+'"'+" and commune='"+str(p[1])+"'"
            print(ip)
        nom=str(z)
        nom=nom.replace("'","''")
        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        selected_features = layer.selectedFeatures()
        if self.comm=='INTERCOMMUNAL':
            z=p[0]
            print(z)
        for feature in selected_features:
            if len(selected_features)!=1:
                self.iface.messageBar().pushInfo("Info",": Plusieurs voies sont sélectionnées. Sélectionnez-en un seul ! !!")
                return
            else:
                com=feature["commune"]
                layer.startEditing()
                feature['new_name']=z
                self.id_voie=feature['id_voie']
                layer.updateFeature(feature)
                layer.commitChanges()
        lists = QgsProject.instance().mapLayersByName("toponymes")[0]
        lista=sorted(lists.getFeatures(ip),key=lambda feature:feature["id"])
        lists.startEditing()
        print(lista)
        for i in lista:
            print(i["id"])
            print('i nume='+i["nom_propose"])
            i["observation"]='Attribué'
            i["gid_ati"]=self.id_voie
            lists.updateFeature(i)
            print(i["gid_ati"])

        lists.commitChanges()
        self.connstr="dbname='" + self.DBNAME + "' host='" + self.HOST + "'port='"+self.PORT+"' user='" + self.USERNAME + "' password='" + self.PASSWORD + "'"
        conn = psycopg2.connect(self.connstr)
        cur = conn.cursor()
        sql="Update public.toponymes set observation='Attribué' where nom_propose='"+nom+"' and commune='"+com+"';"
        sql1='Update public.toponymes set gid_ati='+str(self.id_voie) +" where nom_propose='"+nom+"' and commune='"+com+"';"
        print(sql)
        cur.execute(sql)
        cur.execute(sql1)
        conn.commit()
        cur.close()
        conn.close()
        self.dockwidget.radioButton_3.setChecked (True)
        self.selectTypo()
        #self.dockwidget.radioButton_9.setChecked (True)

    def changeN(self):
        if len(self.dockwidget.codl.selectedItems()) != 0:
            z=str(self.dockwidget.codl.currentItem().text())

        else:
            self.iface.messageBar().pushInfo("Info",":Sélectionnez-en un nom ! !!")
            return
        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        selected_features = layer.selectedFeatures()
        for feature in selected_features:
            if len(selected_features)!=1:
                self.iface.messageBar().pushInfo("Info",": Plusieurs voies sont sélectionnées. Sélectionnez-en un seul ! !!")
                return
            else:
                nom=feature['new_name']
                print(nom)
                com=feature["commune"]
        lists = QgsProject.instance().mapLayersByName("toponymes")[0]
        lista=sorted(lists.getFeatures(),key=lambda feature:feature["id"])
        for i in lista:
            if i['nom_propose']==nom and i["commune"]==com:
                print(nom)
                lists.startEditing()
                print(i["id"])
                i["observation"]=NULL
                i.setAttribute('observation', NULL)
                i["gid_ati"]=NULL
                i.setAttribute('gid_ati', NULL)
                lists.updateFeature(i)
                self.connstr="dbname='" + self.DBNAME + "' host='" + self.HOST + "'port='"+self.PORT+"' user='" + self.USERNAME + "' password='" + self.PASSWORD + "'"
                conn = psycopg2.connect(self.connstr)
                cur = conn.cursor()
                nom=nom.replace("'","''")
                sql="Update public.toponymes set observation=NULL where nom_propose='"+nom+"' and commune='"+com+"';"
                sql1="Update public.toponymes set gid_ati=NULL where nom_propose='"+nom+"' and commune='"+com+"';"
                print(sql)
                print(sql)
                cur.execute(sql)
                cur.execute(sql1)
                conn.commit()
                cur.close()
                conn.close()

            #print(i["gid_ati"])
        lists.commitChanges()

        self.write()

    def descr(self):
        print(len(self.dockwidget.codl.selectedItems()))
        if len(self.dockwidget.codl.selectedItems())==0:
           self.iface.messageBar().pushInfo("Info",": Aucune nom n'est pas sélectionnée!!!")
           return
        lists = QgsProject.instance().mapLayersByName("toponymes")[0]
        z=str(self.dockwidget.codl.currentItem().text())
        layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
        selected_features = layer.selectedFeatures()
        if len(selected_features)!=1:
                self.iface.messageBar().pushInfo("Info",": Aucune voie n'est pas sélectionnée.!!!")
                #self.dockwidget.codl.clear()
                return
        if self.comm!='INTERCOMMUNAL':
            ip="nom_propose="+'"'+str(z)+'"'+"' and commune='"+self.comm+"'"
            print(ip)
        else:
            print(str(z).split('==>'))
            p=str(z).split('==>')
            ip="nom_propose="+'"'+str(z)+'"'+"' and commune='"+str(p[1])+"'"
            print(ip)
        lista=sorted(lists.getFeatures(ip),key=lambda feature:feature["id"])
        self.dockwidget.Description_2.clear()
        for i in lista:
            print(i["id"])
            self.dockwidget.Description_2.insertPlainText(str(i["description"]))
        self.dockwidget.toolBox.setCurrentIndex(2)

    def retourn(self):
        self.dockwidget.toolBox.setCurrentIndex(1)


    # def radio1_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='PERSONNALITES DE COMMUNE'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))



    # def radio2_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='PERSONNALITES DE COMMUNE'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    # def radio9_clicked(self, enabled):
    #     if enabled:
    #         self.selectNom()

    # def radio3_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='REGIONS LOCALITES ETHNIES'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    # def radio4_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='FAUNE'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))


    #     else:
    #         self.selectNom()

    # def radio5_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='HYDROGRAPHIE'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    # def radio6_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='PLANTES'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    # def radio7_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='PLANTES'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #     else:
    #         self.selectNom()

    # def radio7_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='CONCEPTS CULTUREL'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #     else:
    #         self.selectNom()


    # def radio8_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='RELIEF'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    # def radio10_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='CONTINENTS PAYS CAPITALES'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    # def radio11_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='METS ET GASTRONOMIE'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    # def radio12_clicked(self, enabled):
    #     if enabled:
    #         tip=''
    #         c=False
    #         self.dockwidget.label_8.setText('')
    #         layer=QgsProject.instance().mapLayersByName(self.tble_voirie)[0]
    #         selected_features = layer.selectedFeatures()
    #         print(len(selected_features))
    #         print(c)
    #         if len(selected_features)!=0:
    #             print('da')
    #             for j in selected_features:
    #                 tip=j['type_voie']
    #                 com=j["commune" ]
    #                 self.comm=j["commune" ]
    #                 if tip==None:
    #                     tip='-'
    #                 self.dockwidget.label_8.setText(tip)
    #                 self.id_voie=j["id_voie"]
    #             print(tip)

    #             inter="commune='"+str(com)+"' and typologie='SATELLITES ET PLANETES'"
    #             print(inter)
    #             lists = QgsProject.instance().mapLayersByName("toponymes")[0]
    #             if com=='INTERCOMMUNAL':
    #                 lista=sorted(lists.getFeatures("typologie='Personnalités'"),key=lambda feature:feature["gid"])
    #             else:
    #                 lista=sorted(lists.getFeatures(inter),key=lambda feature:feature["id"])
    #             self.dockwidget.codl.clear()
    #             print(len(lista))
    #             for i in lista:
    #                 self.gid=i["id"]
    #                 #print(self.gid)
    #                 c=True
    #                 self.pro=True
    #                 if i["observation"]==None:
    #                     if com=='INTERCOMMUNAL':
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"])+'==>'+str(i["commune"]))
    #                     else:
    #                         self.dockwidget.codl.addItem(str(i["nom_propose"]))
    #             if c==False and self.pro==False:

    #                 for i in lista:
    #                     self.dockwidget.codl.addItem(str(i["nom_propose"]))

    #     else:
    #         self.selectNom()

    #--------------------------------------------------------------------------
    def run(self):
        """Run method that loads and starts the plugin"""

        if not self.pluginIsActive:
            self.pluginIsActive = True

            #print "** STARTING NomVoie"
            # dockwidget may not exist if:
            #    first run of plugin
            #    removed on close (see self.onClosePlugin method)
            if self.dockwidget == None:
                # Create the dockwidget (after translation) and keep reference
                self.dockwidget = NomVoieDockWidget()

            # connect to provide cleanup on closing of dockwidget
            self.dockwidget.closingPlugin.connect(self.onClosePlugin)

            # show the dockwidget
            # TODO: fix to allow choice of dock location
            self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockwidget)
            self.dockwidget.show()

            canvas = self.iface.mapCanvas()
            canvas.selectionChanged.connect(self.select)
            self.dockwidget.Load.clicked.connect(self.write)
            self.dockwidget.decr.clicked.connect(self.descr)
            self.dockwidget.back.clicked.connect(self.retourn)
            self.dockwidget.comboBox_trie.activated.connect(self.TrieTypo)
            # self.dockwidget.radioButton.toggled.connect(self.radio1_clicked)
            #self.dockwidget.radioButton_9.toggled.connect(self.radio9_clicked)
            #self.dockwidget.radioButton_2.toggled.connect(self.radio2_clicked)
            # self.dockwidget.radioButton_3.toggled.connect(self.radio3_clicked)
            # self.dockwidget.radioButton_4.toggled.connect(self.radio4_clicked)
            # self.dockwidget.radioButton_5.toggled.connect(self.radio5_clicked)
            # self.dockwidget.radioButton_6.toggled.connect(self.radio6_clicked)
            #self.dockwidget.radioButton_7.toggled.connect(self.radio7_clicked)
            # self.dockwidget.radioButton_8.toggled.connect(self.radio8_clicked)
            # self.dockwidget.radioButton_10.toggled.connect(self.radio10_clicked)
            # self.dockwidget.radioButton_11.toggled.connect(self.radio11_clicked)
            # self.dockwidget.radioButton_12.toggled.connect(self.radio12_clicked)
            self.dockwidget.prev.clicked.connect(self.Prev)
            self.dockwidget.next.clicked.connect(self.Next)
            self.dockwidget.BTN_START.clicked.connect(self.log)
            self.dockwidget.btn_Com.clicked.connect(self.log_1)
            self.dockwidget.Load_2.clicked.connect(self.changeN)
